Allow for .precious.toml as an alternate default config file name
houseabsolute/precious pull request #21
Opened 2022-02-18 23:13 UTC by oalders

- Allow for .precious.toml as a default config file name
- Use a constant for precious.toml in tests

2022-02-18 23:33 UTC, oalders commented
This is my first ever Rust code, so I'm open to lots of harsh feedback. 📣

2022-02-18 23:39 UTC, autarch requested changes
Just a few small comments. Overall this looks good, but it also needs doc updates (just the `README.md`).

2022-02-19 01:14 UTC, oalders commented on src/precious.rs
> +        return file.exists();
In that case I get

>  1 src/precious.rs|688 col 8-22 error| mismatched types: implicitly returns `()` as its body has no tail or `return` expression
>  2 src/precious.rs|688 col 40-43 error| mismatched types: expected `bool`, found `()`

2022-02-19 01:19 UTC, oalders commented on src/precious.rs
> +        if !file.exists() {
I ended up with something like:

```rust
    fn default_config_file(root: &Path) -> PathBuf {
        let root_dir = root.to_path_buf();
        let mut file;
        for name in ["precious.toml", ".precious.toml"] {
            file = root_dir.clone();
            file.push(name);
            if file.exists() {
                return file;
            }
        }
        file
    }
```

That leaves me with 

> src/precious.rs|316 col 9-12 error| use of possibly-uninitialized variable: `file`: use of possibly-uninitialized `file`

2022-02-19 01:27 UTC, oalders commented
I'm ready for my next round of feedback. 😄

2022-02-19 16:18 UTC, autarch commented on src/precious.rs
> +        if !file.exists() {
I pushed a change to do this with an iterator using `itertools` (Rust's `List::SomeUtils`), but then I realized that'd bump the itertools dependency version up, and I had tried to lower that version for the benefit of Debian, so I'm going to do the same thing with an iterator manually.

2022-02-19 16:52 UTC, autarch commented
I ended up merging my version from the CLI. I would have tried to give you feedback so you could do it yourself, but the only way I could get the logic I wanted to work was to actually implement and test it.

This will be in the next release.

2022-02-19 16:52 UTC, closed without merging

2022-02-19 17:09 UTC, oalders commented
Great. Thanks for doing that! Was a good learning experience for me.